language: node_js
node_js:
  - 8
services:
  - mysql
install:
  - npm install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS turing_test;'
script:
  - npm test
after_success:
  - npm run coverage
