language: node_js
node_js:
  - 8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS turing_test;'
install:
  - npm install
before_script:
  - npm run pretest
script:
  - npm test
after_success:
  - npm run coverage
