language: node_js
node_js:
  - stable
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS turing_test;'
  - mysql -u root -D turing_test < ./database/dump.sql
install:
  - npm install
before_script:
  - npm run pretest
script:
  - npm run test
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coverage
